[build]
  command = "vite build"
  publish = "/dist"  

[dev]
  framework = "vite"  

[prerender]
  enabled = true
  include = "/*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force=false